### ISSUE TITLE
SyntaxError: Unexpected character '#'  when running list-deps

### ISSUE THREAD

**Issue by drdee** [mrjoelkemp/node-list-dependencies#1]
``` shell
/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/node_modules/acorn/acorn.js:335
    throw err;
          ^
SyntaxError: Unexpected character '#' (1:0)
    at raise (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/node_modules/acorn/acorn.js:333:15)
    at readToken (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/node_modules/acorn/acorn.js:901:7)
    at initParserState (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/node_modules/acorn/acorn.js:321:5)
    at Object.exports.parse (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/node_modules/acorn/acorn.js:47:5)
    at module.exports.parse (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/index.js:22:16)
    at module.exports.walk (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/node_modules/node-source-walk/index.js:68:33)
    at module.exports (/usr/local/lib/node_modules/list-dependencies/node_modules/detective-amd/index.js:13:10)
    at printDependencies (/usr/local/lib/node_modules/list-dependencies/bin/list-deps.js:39:22)
    at /usr/local/lib/node_modules/list-dependencies/bin/list-deps.js:29:5
    at /usr/local/lib/node_modules/list-dependencies/node_modules/node-dir/lib/readfiles.js:99:34
```

**Comment by mrjoelkemp** [comment]
Interesting! Thanks for reporting @drdee. I'll confirm if I need to strip these out before passing the content to the parser or if this is a known bug with the Acorn parser.

**Comment by drdee** [comment]
no problem!

**Comment by mrjoelkemp** [comment]
The parser hasn't yet released the ability to handle hashbangs (that functionality was merged 5 days ago), so I patched it in an underlying library. 

I also added support for commonjs and es6 modules to this library. v1.0.0 has been released. 

Thanks again for contributing.

**Comment by drdee** [comment]
Awesome! thanks a lot for the quick turn around time!
